### ISSUE TITLE
Setting only_known leads to loads of `retrieving values from unparsed Parameters` warnings

### ISSUE THREAD

**Issue by JethroMV** [alunduil/crumbs#34]
When you parse with `only_known` set, every time we lookup a valid value we get warnings:

> retrieving values from unparsed Parameters

The docs explain that `parsed` is not set when `only_known` is set.  Would it make sense to disable this warning in the case that `only_known` is set?  Or consider the parameters as `parsed` anyway? I can't find the reason for `parsed` not being set alongside `only_known`.

```
from crumbs import Parameters

parameters = Parameters()
parameters.add_parameter(options=["--foo"])
parameters.parse(only_known=True)
parameters["foo"]

```

**Comment by alunduil** [comment]
That reason that parsed wasn't set is this use case is intended to allow for early parsing of options that might influence later options.  So by setting parsed here we would remove that use case.

As for removing the warning?  I still think it makes sense.  What are you trying to do that doesn't fit inside the use case of parse only known to influence further set options?

**Comment by JethroMV** [comment]
Thanks for the quick response!
I'm trying to use crumbs within a Django app.  Our Django `settings.py` gets a crumbs Parameters object and uses it to set various properties.  This file is read whenever Django runs, but also when using it's dev commands, things like making database migrations and checking the project.

Without `only_know` set, these Django `manage.py` commands fail - crumbs sees the Django specific params and correctly says that those parameters have not been added.

Adding `only_known` in this case was an attempt to have crumbs ignore params which are not intended for it to parse.

**Comment by alunduil** [comment]
Hmm, that's an interesting case.  What about suppressing warning around that particular set of calls using the python warnings semantics?  Would that be sufficient?  I feel that the normal case makes sense for the warnings but your case should be called out as explicitly not wanting that semantic.

If that doesn't fit your use case, I'd probably want to dig into why use crumbs rather than a more up to date option parsing system?

Let me know what you're thinking.

**Comment by JethroMV** [comment]
I think you're right, suppressing the warnings would work well and be explicit in saying that we don't mind that extra params have been added.

We're using crumbs because it's simple and awesome :D Works great moving codebases to the containerised world where ENV vars are important alongside config files, and having command line flags alongside that is even better.
Thanks for a great project.

**Comment by alunduil** [comment]
@JethroMV thanks!  If you're interested in continuing to use crumbs it could definitely use an update for python3 with a few extras.  I'd love a little help since I don't get to these old python projects very much anymore.
